name: Test Lume build

on: push

jobs:
  build-and-deploy:
    name: Test Lume Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up deno
        uses: denolib/setup-deno@v2
        with:
          deno-version: v1.21.0

      - name: Run Lume build script
        run: deno run -A https://deno.land/x/lume/ci.ts

